chore: improve wikipedia download script python 3.10 handling (#153)
Summary:

- Added a strict Python 3.10 detector, inspecting python3.10, python3,
or python, only use it if it is 3.10. Otherwise exit with an explicit
error.
- We no longer invoke `pip` or `pip3` directly because:

1. It won't work on externally managed environments. For example, macOS:

     ```sh 
     $ pip3 install xxx 
     error: externally-managed-environment
     ```

  2. It may not be the pip associated with Python 3.10